server :
  port : 8094
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: root
    password: a1234
  jpa:
    open-in-view: false

mybatis:
  config: mybatis/mybatis.config
  mapper-locations: mybatis/mappers/*.xml


