server :
<<<<<<< HEAD
  port : 8094
=======
  port : 8095
>>>>>>> 9174528b32d015711b6f045e1a44f86a13fd6909
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: root
    password: a1234
  jpa:
    open-in-view: false
<<<<<<< HEAD
=======
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true

>>>>>>> 9174528b32d015711b6f045e1a44f86a13fd6909

mybatis:
  config: mybatis/mybatis-config.xml
  mapper-locations: mybatis/mappers/*.xml


