server :
  port : 8095
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: root
    password: a1234
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true


mybatis:
  config: mybatis/mybatis-config.xml
  mapper-locations: mybatis/mappers/*.xml


